# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: first_test_workflow
env:
  APPLICATION_NAME       : "My django converter"
  DEPLOY_PACKAGE_NAME    : "django_deploy_ver_${{ github.sha }}"

on:
  push:
    branches: [ "main" ]

jobs:
  my_testing:
    runs-on: ubuntu-lateststzs

    steps:
      
      - name: Print Hello Message in 'testing'
        run : echo "Hello from my_testing job"
      
      - name: Execute few comands
        run: |
          echo "Hello message1"
          echo "Hello message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: ls -la
        
      - name: Git clone project
        uses: actions/checkout@v1
        
      - name: List current folder
        run: ls -la
      
  my_deploy:
    
    runs-on: ubuntu-latest
    needs: [my_testing]
    env: 
      VAR1: "Job lavel variable 1"
      VAR2: "Job lavel variable 2"
    
    steps:
      
      - name: Print Hello Message in 'deploy'
        run : echo "Hello from my_deploy job"
        
      - name: Print env variables
        run: |
          echo "Var 1 = ${{ env.VAR1 }}"
          echo "Var 2 = ${{ env.VAR2 }}"
          echo "Var 3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "Super local env variable"
        
      - name: Printing deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Test packages 1
        run: aws --version
        
      - name: Test packages 2
        run: zip --version
