# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: first_test_workflow

on:
  push:
    branches: [ "main" ]


jobs:
  my_testing:

    runs-on: ubuntu-latest

    steps:
      
      - name: Print Hello Message in 'testing'
        run : echo "Hello from my_testing job"
  
  my_deploy:
    
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      
      - name: Print Hello Message in 'deploy'
        run : echo "Hello from my_deploy job"
